package com.jdiaz.parte11curso_poo_interfaces_repositorio.repositorio;

public interface OrdenablePaginableCrudRepositorio extends OrdenableRepositorio, PaginableRepositorio, CrudRepositorio,ContableRepositorio{

}
